### ISSUE TITLE
cargo test failed in windows

### ISSUE THREAD

**Issue by quantrpeter** [simon-frankau/galette#9]
hi

C:\workspace\galette>cargo --version
cargo 1.72.0 (103a7ff2e 2023-08-15)

![image](https://github.com/simon-frankau/galette/assets/50471577/9a942293-15ce-41e4-9355-3ba8a3f78686)

**Comment by simon-frankau** [comment]
Hi. Sorry for the slow response, somehow the github notification ended up in my spam folder.

First off, thanks for the report!

Second, my suspicion lies with the `test_bin` package - that's the piece of code that tries to run the executable, and I don't think I'm doing anything particularly fancy in my code that could cause a bug. Unfortunately, because I don't have a working Rust install on Windows, I'm not in a particularly good position to make a minimal case that I can raise with the owners of `test_bin`. From the screenshot provided, I'm wondering if Windows builds having a hash added to their name breaks assumptions from `test_bin`?

Anyway, so far I've asked the dependency owner if there's any *known* issues with `test_bin` and Windows (https://github.com/MichaelMcDonnell/test_bin/issues/6), and I guess we'll take it from there?

Cheers,
Simon.

**Comment by simon-frankau** [comment]
The update on https://github.com/MichaelMcDonnell/test_bin/issues/6 makes me realise it probably is a galette problem after all. D'oh. I'll see what I can do about having the tests run on a platform without "diff" installed.

**Comment by simon-frankau** [comment]
Hi.

Sorry it's taken so long to try to fix this - I've had some issues with my health. This is hopefully now fixed in https://github.com/simon-frankau/galette/commit/85908d45bc401224b25b49da75aaff53c191a805 , although I don't have a Windows dev box to test on.

Thanks for your patience.

I'm closing this issue now, to make it easier to see what I've yet to address, but please do re-open if you have any issues.

Thanks,
Simon.
